apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: git-repository
  namespace: git
spec:
  interval: 5m
  url: https://github.com/stefanprodan/podinfo
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: my-kustomization
  namespace: default
spec:
  interval: 10m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: git-repository
    namespace: git
  path: "./kustomize"
  prune: true
  timeout: 1m